spring:
  datasource:
    url: jdbc:mysql://mysql-boostimdata:3306/boostimdata?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true
    username: root
    password: boostim#data

authserver:
  url: http://web-boostimauth:9000

appserver:
  url: "*"

centerserver:
  url: http://web-boostimcenter:9510